In [1]:
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error, r2_score
import pandas as pd

In [2]:
X_train = pd.read_csv('csv/predictors_withsom_scaled_train.csv')
X_test = pd.read_csv('csv/predictors_withsom_scaled_test.csv')
y_train = pd.read_csv('csv/target_train.csv')
y_test = pd.read_csv('csv/target_test.csv')

In [3]:
regions_train = y_train[['region']]
regions_test = y_test[['region']]
#X_train = X_train.drop('region', axis=1)
#X_test = X_test.drop('region', axis=1)
y_train = y_train.drop('region', axis=1)
y_test = y_test.drop('region', axis=1)

In [4]:
ridge_regressor = Ridge()
lasso_regressor = Lasso()

# Подбор параметра регуляризации с помощью кросс-валидации
> В датасете помимо исходных переменных присутствует закодированная (One-Hot) переменная кластерного деления объектов

## Сетка параметров

In [9]:
grid_params = {
    'alpha': [0.01, 0.05, 0.1, 0.5, 1, 5, 10]
}

## Ridge

### Перебор параметров по сетке

In [36]:
grid_ridge = GridSearchCV(ridge_regressor, grid_params, cv=5, verbose=1, scoring='r2')
grid_ridge.fit(X_train, y_train)

Fitting 5 folds for each of 7 candidates, totalling 35 fits

GridSearchCV(cv=5, estimator=Ridge(),
             param_grid={'alpha': [0.01, 0.05, 0.1, 0.5, 1, 5, 10]},
             scoring='r2', verbose=1)

### Лучшая модель

In [37]:
ridge_regressor = grid_ridge.best_estimator_
ridge_params = grid_ridge.best_params_

### Лучший параметр регуляризации

In [38]:
ridge_params['alpha']

10

### Предсказанные значения

In [39]:
y_pred = ridge_regressor.predict(X_test)
y_train_pred = ridge_regressor.predict(X_train)

In [40]:
response_test = pd.concat([regions_test, pd.Series(y_pred, name='ratio_underage_partic_predicted'), y_test], axis=1)
response_train = pd.concat([regions_train, pd.Series(y_train_pred, name='ratio_underage_partic_predicted'), y_train], axis=1)

In [50]:
response_train

,region,ratio_underage_partic_predicted,ratio_underage_partic
0,Камчатский край,0.590673,0.723200
1,Чеченская Республика,0.005275,0.003583
2,Чувашская Республика - Чувашия,0.289051,0.339983
3,Рязанская область,0.266490,0.253967
4,Республика Калмыкия,0.375474,0.266633
...,...,...,...
63,Ненецкий автономный округ,0.652151,0.709033
64,Ханты-Мансийский автономный округ - Югра,0.336773,0.215500
65,Новосибирская область,0.557687,0.619767
66,Тверская область,0.577046,0.495067
67,Кировская область,0.540033,0.608567

In [51]:
response_test

,region,ratio_underage_partic_predicted,ratio_underage_partic
0,Приморский край,0.638246,0.703667
1,Белгородская область,0.288785,0.243133
2,Красноярский край,0.699101,0.587017
3,Вологодская область,0.579057,0.591933
4,Смоленская область,0.574643,0.596300
5,Сахалинская область,0.761782,0.826383
6,Орловская область,0.426621,0.301567
7,Республика Карелия,0.631097,0.919950
8,Ивановская область,0.478875,0.500083
9,Республика Хакасия,0.581732,0.574600
10,Карачаево-Черкесская Республика,0.224498,0.241683
11,Республика Татарстан,0.160033,0.354267
12,Ростовская область,0.376203,0.338650
13,Омская область,0.542390,0.295333
14,Самарская область,0.287941,0.353017
15,Пензенская область,0.371905,0.302467
16,Астраханская область,0.486103,0.549200

### Метрики

In [41]:
ridge_metrics = pd.DataFrame({
    'MAE':[mean_absolute_error(y_pred, y_test), mean_absolute_error(y_train_pred, y_train)],
    'MAPE':[mean_absolute_percentage_error(y_pred, y_test), mean_absolute_percentage_error(y_train_pred, y_train)],
    'R2':[r2_score(y_pred, y_test), r2_score(y_train_pred, y_train)]
}, index = ['test', 'train'])

In [42]:
ridge_metrics

            MAE      MAPE        R2
test   0.080900  0.209338  0.553889
train  0.075364  0.172264  0.695623

### Коэффициенты

In [43]:
coeffs = pd.DataFrame(ridge_regressor.coef_, index=X_train.columns, columns=['coeffs'])
coeffs

                              coeffs
health_ratio               -0.008872
coeff_Gini                 -0.013334
not_smoking_male%          -0.062134
not_smoking_female%        -0.074541
num_of_criminals           -0.005527
num_of_alcohol_crimes       0.002287
num_of_female_crimes       -0.013848
num_of_drugs_crimes         0.005479
num_of_underaged_criminals  0.074744
life_quality               -0.079765
population_size            -0.033904
num_of_crimes               0.000683
neuron_1                    0.012158
neuron_2                    0.013717
neuron_3                   -0.006522
neuron_4                   -0.000104
neuron_5                   -0.008191
neuron_6                   -0.011335
neuron_7                   -0.015164
neuron_8                    0.013781
neuron_9                    0.005285
neuron_10                  -0.010928
neuron_11                   0.003536
neuron_12                  -0.006735
neuron_13                  -0.006195
neuron_14                  -0.009925
neuron_15                   0.000015
neuron_16                  -0.008408
neuron_17                  -0.010505
neuron_18                  -0.009843
neuron_19                   0.007562
neuron_20                  -0.002297
neuron_21                   0.006357
neuron_22                   0.001724
neuron_23                   0.039450
neuron_24                  -0.008724
neuron_25                  -0.006708
neuron_26                   0.009919
neuron_27                  -0.000830
neuron_28                   0.017216
neuron_29                   0.011794
neuron_30                   0.000000
neuron_31                   0.005702
neuron_32                  -0.001643
neuron_33                  -0.007086
neuron_34                   0.011258
neuron_35                   0.004144
neuron_36                  -0.008363
neuron_37                  -0.012013
neuron_38                  -0.004619
neuron_39                   0.000444
neuron_40                   0.000000
neuron_41                   0.004950
neuron_42                  -0.002774
neuron_43                  -0.008030
neuron_44                   0.004054
neuron_45                   0.000152
neuron_46                   0.000000
neuron_47                   0.005999
neuron_48                  -0.001480

## Lasso

In [44]:
grid_lasso = GridSearchCV(lasso_regressor, grid_params, cv=5, scoring='r2', verbose=1)
grid_lasso.fit(X_train, y_train)

Fitting 5 folds for each of 7 candidates, totalling 35 fits

GridSearchCV(cv=5, estimator=Lasso(),
             param_grid={'alpha': [0.01, 0.05, 0.1, 0.5, 1, 5, 10]},
             scoring='r2', verbose=1)

### Лучшая модель

In [45]:
lasso_regressor = grid_lasso.best_estimator_
lasso_params = grid_lasso.best_params_

### Лучший параметр регуляризации

In [46]:
lasso_params['alpha']

0.01

### Предсказанные значения

In [47]:
y_pred = lasso_regressor.predict(X_test)
y_train_pred = lasso_regressor.predict(X_train)

In [48]:
response_test = pd.concat([regions_test, pd.Series(y_pred, name='ratio_underage_partic_predicted'), y_test], axis=1)
response_train = pd.concat([regions_train, pd.Series(y_train_pred, name='ratio_underage_partic_predicted'), y_train], axis=1)

### Метрики

In [49]:
lasso_metrics = pd.DataFrame({
    'MAE':[mean_absolute_error(y_pred, y_test), mean_absolute_error(y_train_pred, y_train)],
    'MAPE':[mean_absolute_percentage_error(y_pred, y_test), mean_absolute_percentage_error(y_train_pred, y_train)],
    'R2':[r2_score(y_pred, y_test), r2_score(y_train_pred, y_train)]
}, index = ['test', 'train'])
lasso_metrics

            MAE      MAPE        R2
test   0.085775  0.221241  0.501010
train  0.081627  0.187228  0.649349

# Подбор параметра регуляризации с помощью кросс-валидации
> В датасете помимо исходных переменных присутствует единая стандартизованная переменная кластерного деления объектов

In [5]:
X_train = pd.read_csv('csv/predictors_with_onesom_scaled_train.csv')
X_test = pd.read_csv('csv/predictors_with_onesom_scaled_test.csv')
y_train = pd.read_csv('csv/target_train.csv')
y_test = pd.read_csv('csv/target_test.csv')

In [6]:
regions_train = y_train[['region']]
regions_test = y_test[['region']]
#X_train = X_train.drop('region', axis=1)
#X_test = X_test.drop('region', axis=1)
y_train = y_train.drop('region', axis=1)
y_test = y_test.drop('region', axis=1)

In [7]:
ridge_regressor = Ridge()

In [10]:
grid_ridge = GridSearchCV(ridge_regressor, grid_params, cv=5, verbose=1, scoring='r2')
grid_ridge.fit(X_train, y_train)

Fitting 5 folds for each of 7 candidates, totalling 35 fits

GridSearchCV(cv=5, estimator=Ridge(),
             param_grid={'alpha': [0.01, 0.05, 0.1, 0.5, 1, 5, 10]},
             scoring='r2', verbose=1)

In [12]:
ridge_regressor = grid_ridge.best_estimator_
ridge_params = grid_ridge.best_params_

In [13]:
ridge_params['alpha']

5

In [14]:
y_pred = ridge_regressor.predict(X_test)
y_train_pred = ridge_regressor.predict(X_train)

In [15]:
response_test = pd.concat([regions_test, pd.Series(y_pred, name='ratio_underage_partic_predicted'), y_test], axis=1)
response_train = pd.concat([regions_train, pd.Series(y_train_pred, name='ratio_underage_partic_predicted'), y_train], axis=1)

In [16]:
ridge_metrics = pd.DataFrame({
    'MAE':[mean_absolute_error(y_pred, y_test), mean_absolute_error(y_train_pred, y_train)],
    'MAPE':[mean_absolute_percentage_error(y_pred, y_test), mean_absolute_percentage_error(y_train_pred, y_train)],
    'R2':[r2_score(y_pred, y_test), r2_score(y_train_pred, y_train)]
}, index = ['test', 'train'])

In [17]:
ridge_metrics

            MAE      MAPE        R2
test   0.073567  0.197236  0.612736
train  0.074917  0.188645  0.712961

In [64]:
coeffs = pd.DataFrame(ridge_regressor.coef_, index=X_train.columns, columns=['coeffs'])
coeffs

                              coeffs
health_ratio               -0.000551
coeff_Gini                 -0.010537
not_smoking_male%          -0.062791
not_smoking_female%        -0.083598
num_of_criminals           -0.009039
num_of_alcohol_crimes      -0.019151
num_of_female_crimes       -0.027239
num_of_drugs_crimes         0.016761
num_of_underaged_criminals  0.094350
life_quality               -0.091864
population_size            -0.041011
num_of_crimes               0.001973
som_neuron_id               0.026847

In [21]:
float(ridge_regressor.intercept_[0])

0.4770007352843136